version: '3.1'

services:
  mypostgre:
    container_name: healthcare
    image: postgres:latest
    restart: always
    ports:
      - 9433:5432
    environment:
      - POSTGRES_PASSWORD=passpass
      - POSTGRES_USER=root
      - POSTGRES_DB=healthcaredb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      #- C:\ProgramData\DockerDesktop\Postgre\HealthCare:/var/lib/postgresql/data
      -  /Users/talhabuyukkose/DockerVolumes/HealthCareDb:/var/lib/postgresql/data/pgdata